"""Restruct tables

Revision ID: b854d327fb17
Revises: 5b305dbc57d6
Create Date: 2022-04-13 12:06:46.829525

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
from billtitles.models import TitleType

revision = "b854d327fb17"
down_revision = "5b305dbc57d6"
branch_labels = None
depends_on = None


title_types_enum = postgresql.ENUM(*[i.value for i in TitleType], name="titletype")


def upgrade():
    title_types_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("billnumber_idx", table_name="bill")
    op.drop_index("version_idx", table_name="bill")
    op.add_column(
        "bill_titles",
        sa.Column(
            "type",
            sa.Enum("official", "popular", "short", name="titletype"),
            nullable=True,
        ),
    )
    op.add_column(
        "bill_titles",
        sa.Column("As", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    )
    op.drop_index("ix_bill_titlesx_bill_id", table_name="bill_titles")
    op.drop_index("ix_bill_titlesx_is_for_whole_bill", table_name="bill_titles")
    op.drop_index("ix_bill_titlesx_title_id", table_name="bill_titles")
    op.create_index(op.f("ix_bill_titles_As"), "bill_titles", ["As"], unique=False)
    op.create_index(
        op.f("ix_bill_titles_bill_id"),
        "bill_titles",
        ["bill_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bill_titles_is_for_whole_bill"),
        "bill_titles",
        ["is_for_whole_bill"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bill_titles_title_id"),
        "bill_titles",
        ["title_id"],
        unique=False,
    )
    op.alter_column(
        "btiapp_billbasic",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.create_index(
        op.f("ix_btiapp_billbasic_bill_id"),
        "btiapp_billbasic",
        ["bill_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_btiapp_billbasic_bill_number"),
        "btiapp_billbasic",
        ["bill_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_btiapp_billbasic_bill_type"),
        "btiapp_billbasic",
        ["bill_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_btiapp_billbasic_congress"),
        "btiapp_billbasic",
        ["congress"],
        unique=False,
    )
    op.create_index(
        op.f("ix_btiapp_billbasic_id"),
        "btiapp_billbasic",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_btiapp_billbasic_introduced_at"),
        "btiapp_billbasic",
        ["introduced_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_btiapp_billbasic_number"),
        "btiapp_billbasic",
        ["number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_btiapp_billbasic_updated_at"),
        "btiapp_billbasic",
        ["updated_at"],
        unique=False,
    )
    op.create_unique_constraint(None, "btiapp_billbasic", ["bill_number"])
    op.drop_index(
        "btiapp_billstagetitle_bill_basic_id_8cb5909d",
        table_name="btiapp_billstagetitle",
    )
    op.create_index(
        op.f("ix_btiapp_billstagetitle_As"),
        "btiapp_billstagetitle",
        ["As"],
        unique=False,
    )
    op.create_index(
        op.f("ix_btiapp_billstagetitle_bill_basic_id"),
        "btiapp_billstagetitle",
        ["bill_basic_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_btiapp_billstagetitle_id"),
        "btiapp_billstagetitle",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_btiapp_billstagetitle_is_for_portion"),
        "btiapp_billstagetitle",
        ["is_for_portion"],
        unique=False,
    )
    op.create_index(
        op.f("ix_btiapp_billstagetitle_title"),
        "btiapp_billstagetitle",
        ["title"],
        unique=False,
    )
    op.create_index(
        op.f("ix_btiapp_billstagetitle_titleNoYear"),
        "btiapp_billstagetitle",
        ["titleNoYear"],
        unique=False,
    )
    op.create_index(
        op.f("ix_btiapp_billstagetitle_type"),
        "btiapp_billstagetitle",
        ["type"],
        unique=False,
    )
    op.drop_constraint(
        "btiapp_billstagetitl_bill_basic_id_8cb5909d_fk_btiapp_bi",
        "btiapp_billstagetitle",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "btiapp_billstagetitle",
        "btiapp_billbasic",
        ["bill_basic_id"],
        ["id"],
    )
    op.drop_constraint(
        "btiapp_billtitles_bill_basic_id_key",
        "btiapp_billtitles",
        type_="unique",
    )
    op.create_index(
        op.f("ix_btiapp_billtitles_bill_basic_id"),
        "btiapp_billtitles",
        ["bill_basic_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_btiapp_billtitles_id"),
        "btiapp_billtitles",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_btiapp_billtitles_official_title"),
        "btiapp_billtitles",
        ["official_title"],
        unique=False,
    )
    op.create_index(
        op.f("ix_btiapp_billtitles_popular_title"),
        "btiapp_billtitles",
        ["popular_title"],
        unique=False,
    )
    op.create_index(
        op.f("ix_btiapp_billtitles_short_title"),
        "btiapp_billtitles",
        ["short_title"],
        unique=False,
    )
    op.drop_constraint(
        "btiapp_billtitles_bill_basic_id_5a6995e7_fk_btiapp_billbasic_id",
        "btiapp_billtitles",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "btiapp_billtitles",
        "btiapp_billbasic",
        ["bill_basic_id"],
        ["id"],
    )
    op.drop_index("title_idx", table_name="titles")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("title_idx", "titles", ["title"], unique=False)
    op.drop_constraint(None, "btiapp_billtitles", type_="foreignkey")
    op.create_foreign_key(
        "btiapp_billtitles_bill_basic_id_5a6995e7_fk_btiapp_billbasic_id",
        "btiapp_billtitles",
        "btiapp_billbasic",
        ["bill_basic_id"],
        ["id"],
        initially="DEFERRED",
        deferrable=True,
    )
    op.drop_index(
        op.f("ix_btiapp_billtitles_short_title"),
        table_name="btiapp_billtitles",
    )
    op.drop_index(
        op.f("ix_btiapp_billtitles_popular_title"),
        table_name="btiapp_billtitles",
    )
    op.drop_index(
        op.f("ix_btiapp_billtitles_official_title"),
        table_name="btiapp_billtitles",
    )
    op.drop_index(op.f("ix_btiapp_billtitles_id"), table_name="btiapp_billtitles")
    op.drop_index(
        op.f("ix_btiapp_billtitles_bill_basic_id"),
        table_name="btiapp_billtitles",
    )
    op.create_unique_constraint(
        "btiapp_billtitles_bill_basic_id_key",
        "btiapp_billtitles",
        ["bill_basic_id"],
    )
    op.drop_constraint(None, "btiapp_billstagetitle", type_="foreignkey")
    op.create_foreign_key(
        "btiapp_billstagetitl_bill_basic_id_8cb5909d_fk_btiapp_bi",
        "btiapp_billstagetitle",
        "btiapp_billbasic",
        ["bill_basic_id"],
        ["id"],
        initially="DEFERRED",
        deferrable=True,
    )
    op.drop_index(
        op.f("ix_btiapp_billstagetitle_type"),
        table_name="btiapp_billstagetitle",
    )
    op.drop_index(
        op.f("ix_btiapp_billstagetitle_titleNoYear"),
        table_name="btiapp_billstagetitle",
    )
    op.drop_index(
        op.f("ix_btiapp_billstagetitle_title"),
        table_name="btiapp_billstagetitle",
    )
    op.drop_index(
        op.f("ix_btiapp_billstagetitle_is_for_portion"),
        table_name="btiapp_billstagetitle",
    )
    op.drop_index(
        op.f("ix_btiapp_billstagetitle_id"), table_name="btiapp_billstagetitle"
    )
    op.drop_index(
        op.f("ix_btiapp_billstagetitle_bill_basic_id"),
        table_name="btiapp_billstagetitle",
    )
    op.drop_index(
        op.f("ix_btiapp_billstagetitle_As"), table_name="btiapp_billstagetitle"
    )
    op.create_index(
        "btiapp_billstagetitle_bill_basic_id_8cb5909d",
        "btiapp_billstagetitle",
        ["bill_basic_id"],
        unique=False,
    )
    op.drop_constraint(None, "btiapp_billbasic", type_="unique")
    op.drop_index(op.f("ix_btiapp_billbasic_updated_at"), table_name="btiapp_billbasic")
    op.drop_index(op.f("ix_btiapp_billbasic_number"), table_name="btiapp_billbasic")
    op.drop_index(
        op.f("ix_btiapp_billbasic_introduced_at"),
        table_name="btiapp_billbasic",
    )
    op.drop_index(op.f("ix_btiapp_billbasic_id"), table_name="btiapp_billbasic")
    op.drop_index(op.f("ix_btiapp_billbasic_congress"), table_name="btiapp_billbasic")
    op.drop_index(op.f("ix_btiapp_billbasic_bill_type"), table_name="btiapp_billbasic")
    op.drop_index(
        op.f("ix_btiapp_billbasic_bill_number"), table_name="btiapp_billbasic"
    )
    op.drop_index(op.f("ix_btiapp_billbasic_bill_id"), table_name="btiapp_billbasic")
    op.alter_column(
        "btiapp_billbasic",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.drop_index(op.f("ix_bill_titles_title_id"), table_name="bill_titles")
    op.drop_index(op.f("ix_bill_titles_is_for_whole_bill"), table_name="bill_titles")
    op.drop_index(op.f("ix_bill_titles_bill_id"), table_name="bill_titles")
    op.drop_index(op.f("ix_bill_titles_As"), table_name="bill_titles")
    op.create_index(
        "ix_bill_titlesx_title_id", "bill_titles", ["title_id"], unique=False
    )
    op.create_index(
        "ix_bill_titlesx_is_for_whole_bill",
        "bill_titles",
        ["is_for_whole_bill"],
        unique=False,
    )
    op.create_index("ix_bill_titlesx_bill_id", "bill_titles", ["bill_id"], unique=False)
    op.drop_column("bill_titles", "As")
    op.drop_column("bill_titles", "type")
    op.create_index("version_idx", "bill", ["version"], unique=False)
    op.create_index("billnumber_idx", "bill", ["billnumber"], unique=False)
    # ### end Alembic commands ###
    title_types_enum.drop(op.get_bind())
